"""add type to transactions

Revision ID: 96600ed49020
Revises: 8e4e5efa635e
Create Date: 2026-01-28 22:56:47.702748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96600ed49020'
down_revision = '8e4e5efa635e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add type column with default value 'expense'
    op.add_column('transactions', sa.Column('type', sa.String(length=10), nullable=False, server_default='expense'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
